# Numpy & Pandas 101 for ML

_A more detailed tutorail is hrojas-learn-pandas-ae349241f067. Can be found in my dropbox, machine learning folder_

 ## 1. A simple start for Numpy

### Statistic operations
Numpy has some buil-in functions for statistic operations like mean, mode and std (stands for standard deviation).

In [1]:
import numpy as np

numbers = [1,2,3,4,5]

In [2]:
print np.mean(numbers), np.median(numbers), np.std(numbers)

3.0 3.0 1.41421356237


### Specify element type 
We can specify the type of data when creating or converting numpy arrays

In [3]:
print np.array(numbers, float)
print np.array(numbers)

[ 1.  2.  3.  4.  5.]
[1 2 3 4 5]


### Convenient operations and calculations
We can create 2 dimension Matrix, index and slice like Python lists. Moreover, numpy array has some convenience features for element operation and array/matrix operation.

In [7]:
ary_1 = np.array([numbers,numbers], int)
print ary_1
print ary_1[1][:], ary_1[1][1] # : cuts all the array 
ary_1[1] = 0
ary_1[0][1] = 0
print ary_1

[[1 2 3 4 5]
 [1 2 3 4 5]]
[1 2 3 4 5] 2
[[1 0 3 4 5]
 [0 0 0 0 0]]


In [20]:
ary_2 = ary_1*2
print ary_1, '\n', ary_2, '\n'
print 'ary_1 + ary_2 = ', ary_1 + ary_2, '\n'
print 'ary_1 * ary_2 = ', ary_1 * ary_2, '\n'
# * is element * element

[[1 0 3 4 5]
 [0 0 0 0 0]] 
[[ 2  0  6  8 10]
 [ 0  0  0  0  0]] 

ary_1 + ary_2 =  [[ 3  0  9 12 15]
 [ 0  0  0  0  0]] 

ary_1 * ary_2 =  [[ 2  0 18 32 50]
 [ 0  0  0  0  0]] 



Also, statistic functions like mean and median are utilizable for array/matrix

In [25]:
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([[6], [7], [8]], float)
print np.mean(array_1),np.mean(array_2)
print np.dot(array_1,array_2)

2.0 7.0
[ 44.]


## 2. A simple start for Pandas

### Intro
We store and reference datas with pandas __DataFrame__, a __DataFrame__ is a two dimensional __labeled__ data structure with columns which can be different types if necessary, like string, int, float and boolear. If we don't specify a value, it shows NaN

### Create a  pandas data Series

In [44]:
import pandas as pd

s1 = pd.Series(['Dave', 'Cheng-Han', 'Udacity', 42, -1789710578])
print s1

0           Dave
1      Cheng-Han
2        Udacity
3             42
4    -1789710578
dtype: object


Choose data with index

In [45]:
s2 = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
print s2['Instructor']
print ""
print s2[['Instructor', 'Curriculum Manager', 'Course Number']]
print ""
cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                             'Puppy', 'Kitten'])
print cuteness
print ""
print cuteness > 3
print ""
print cuteness[cuteness > 3]

Dave

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
dtype: object

Cockroach    1
Fish         2
Mini Pig     3
Puppy        4
Kitten       5
dtype: int64

Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool

Puppy     4
Kitten    5
dtype: int64


### Create a pandas DataFrame

In [79]:
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data)
print football
print ' '
print football.dtypes
print ""
print football.describe() #useful for seeing basic statistics of the dataframe's numerical columns
print ""
print football.head() # first 5 rows
print ""
print football.tail() # last 5 rows

   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012
 
losses     int64
team      object
wins       int64
year       int64
dtype: object

          losses       wins         year
count   8.000000   8.000000     8.000000
mean    6.625000   9.375000  2011.125000
std     3.377975   3.377975     0.834523
min     1.000000   4.000000  2010.000000
25%     5.000000   7.500000  2010.750000
50%     6.000000  10.000000  2011.000000
75%     8.500000  11.000000  2012.000000
max    12.000000  15.000000  2012.000000

   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packer

### Access data in DataFrame

In [58]:
print football[['team','wins']]
# for single columns out, we can shorten the syntax
print ' '
print football.team

      team  wins
0    Bears    11
1    Bears     8
2    Bears    10
3  Packers    15
4  Packers    11
5    Lions     6
6    Lions    10
7    Lions     4
 
0      Bears
1      Bears
2      Bears
3    Packers
4    Packers
5      Lions
6      Lions
7      Lions
Name: team, dtype: object


Use the data index or default index number

In [54]:
football.loc[1]

losses        8
team      Bears
wins          8
year       2011
Name: 1, dtype: object

Call data with specified conditions

In [56]:
football[football['wins'] >= 10][['team','wins']]

team  wins
0    Bears    11
2    Bears    10
3  Packers    15
4  Packers    11
6    Lions    10

More actions can be done by different methods

In [80]:
print football
print ' '
print football.iloc[[0]] #iloc works on the positions in the index (so it only takes integers)
print ""
print football.loc[[0]] #loc works on labels in the index.

print ""
print football[3:5]
print ""
print football[football.wins > 10]
print ""
print football[(football.wins > 10) & (football.team == "Packers")] # and, or -- & |

   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012
 
   losses   team  wins  year
0       5  Bears    11  2010

   losses   team  wins  year
0       5  Bears    11  2010

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
0       5    Bears    11  2010
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012


### Pandas Vectorized methods
Consider a DataFrame as a matrix, vectorized methods are like matrix add\time\divid etc. 

In [74]:
d = {'one':pd.Series([1,2,3,4,5],index = ['a','b','c','d','e']),
        'two':pd.Series([1,2,3],index = ['a','b','c'])}
df = pd.DataFrame(d)

print df.apply(np.mean)
print df['one'].map(lambda x:x > 1)
print df.applymap(lambda x:x > 1)

one    3.0
two    2.0
dtype: float64
a    False
b     True
c     True
d     True
e     True
Name: one, dtype: bool
     one    two
a  False  False
b   True   True
c   True   True
d   True  False
e   True  False
