# Scikit-learn in machine learning 101

## Intro
scikit-learn, aka sklearn, is a python module which is often used in machine learning. With sklearn functions, we can do calculate, operate and predicte actions on a dataset, and only a line a two codes are needed to finish these actions.

### A simple example about Gausisian Naive Bayes

Prepare two arrays, input x and output y.

In [19]:
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

Create a GuassianNB container and fit test data. Then predict a new input.

In [26]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X,Y)
clf.predict([[0.8,1]])

array([2])

## Nature of Data
There is several data types, like numeric data, categorical data, time series data etc. Many algorithms assume that input data is numerical, so it is often needed to convert categorical data to numerical data that represents the same patterns
### Encoding using sklearn
Encoding in sklearn is done using __prepricessing__ module, which have two forms of encoding, the __LabelEncoder__ and the __OneHotEncoder__

In [40]:
from sklearn import preprocessing
import pandas

Create a sample_data with a column whose values we want to transform from categories to integers.

In [41]:
sample_data = {'name': ['Ray', 'Adam', 'Jason', 'Varun', 'Xiao'],
               'health':['fit', 'slim', 'obese', 'fit', 'slim']}
data = pandas.DataFrame(sample_data, columns=['name','health']) 
# columns =  confirms the order and whether include the column or nort
print data

    name health
0    Ray    fit
1   Adam   slim
2  Jason  obese
3  Varun    fit
4   Xiao   slim


We have 3 different labels that we are looking forward to categorize:slime, fit, obese. To do this, we will call LabelEncoder and fit the data

In [44]:
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit(data.health)

LabelEncoder()

After fitted the label encoder to the column we need to encode, we can transform that column to integer data based on the different labels found in the column

In [45]:
 label_encoder.transform(data.health)

array([0, 2, 1, 0, 2], dtype=int64)

And we can simply combine the two functions into one ```fit_transform()``` function like below

In [47]:
label_encoder.fit_transform(data.health)

array([0, 2, 1, 0, 2], dtype=int64)

For One_hot Encoder, it's like codes below in pandas. 

In [49]:
pandas.get_dummies(data.health)

fit  obese  slim
0    1      0     0
1    0      0     1
2    0      1     0
3    1      0     0
4    0      0     1

But, as we can see, a large scale matrix is generated to describe the catagory. Each row of the matrix contains only one non-zero element, and all non-zero element is 1. That's why we need __One Hot Encoder__ to deal with it.

In [52]:
ohe = preprocessing.OneHotEncoder() #create ohe object
label_encoded_data = label_encoder.fit_transform(data.health)
print ohe.fit_transform(label_encoded_data.reshape(-1,1))

  (0, 0)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 0)	1.0
  (4, 2)	1.0
